name: Test Github Actions Workflow

on:
  push:
    branches:
      - release/development
      - release/production  # ✅ Trigger เมื่อ push เข้า release/production ด้วย
  workflow_dispatch:  # ✅ สามารถรันเองได้จาก GitHub UI


jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build Project
        run: dotnet publish -c Release -o out

  deploy-development:
    runs-on: ubuntu-latest
    needs: build-app
    if: github.ref == 'refs/heads/release/development'  # ✅ ทำงานเฉพาะ branch development

    steps:
      - name: Simulate Deploy to Development
        run: echo "Deploying to Huawei Cloud Development..."

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-app
    if: github.ref == 'refs/heads/release/production'  # ✅ ทำงานเฉพาะ branch production

    steps:
      - name: Simulate Deploy to Production
        run: echo "🚀 Deploying to Huawei Cloud Production..."
